name: Lelouchcr's blog
description: Blogging about the programming life
meta_description: "lelouchcr's blog"
baseurl: /

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

#pygments: true
# highlighter: true
# rouge: true

# logo: /assets/images/153xx.jpg
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'caorong.github.io'
author:         'Lelouchcr'



